version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Luong_2003"
    ports:
      - "1444:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql
    networks:
      - mynetwork

  orderapi:
    image: orderapi
    build:
      context: .
      dockerfile: OrderAPI/Dockerfile
    ports:
      - "8082:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Server=host.docker.internal,1433;Database=OrderApi1;User Id=sa;Password=Luong_2003;TrustServerCertificate=True;
    depends_on:
      - sqlserver
    networks:
      - mynetwork

  paymentapi:
    image: paymentapi
    build:
      context: .
      dockerfile: PaymentAPI/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ConnectionStrings__DefaultConnection=Server=host.docker.internal,1433;Database=PaymentApi1;User Id=sa;Password=Luong_2003;TrustServerCertificate=True;
    depends_on:
      - sqlserver
    networks:
      - mynetwork

volumes:
  sqlserverdata:

networks:
  mynetwork:
    driver: bridge
